version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env 
    environment:
      - FLASK_ENV=development
    networks:
      - es_network
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=mehrez
      - RABBITMQ_DEFAULT_PASS=bey
    networks:
      - es_network
  celery_worker:
    build: .
    command: celery -A make_celery  worker --loglevel=INFO --pool=solo 
    env_file:
      - .env  
    depends_on:
      - rabbitmq
    networks:
      - es_network

  celery_beat:
    build: .
    command: celery -A search_module  beat --loglevel=INFO -l debug
    env_file:
      - .env  
    depends_on:
      - rabbitmq
    networks:
      - es_network

networks:
  es_network:
    external: true